### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by JasonKaze** [AreteQin/MECH371#1]
Hi I want to know what does T_m=0.2 and N=30 does in the Simulink file here's what I have right now
![WhatsApp Image 2023-09-13 at 19 09 23](https://github.com/AreteQin/MECH371/assets/145140100/898a0378-f611-4233-a148-59279508c1c3)

Can you also Verify if my simulink is built correctly, it's been a while since I used it.
Thank you

**Comment by AreteQin** [comment]
Hi
You need to put them in your transfer functions.

**Comment by JasonKaze** [comment]
thanks but can you give me a better idea where in the transfer function can I place these values? The transfer function I think you are talking about the 120/(s+1) 
<img width="438" alt="image" src="https://github.com/AreteQin/MECH371/assets/145140100/8db4592f-187e-47bc-9d9b-72d1322682ca">
I am not sure where in the parameter I can put in the T_m and N value. Would you also mind to explain what's the meaning of these two values? I am very confused

**Comment by AreteQin** [comment]
Yes, please replace the first one with tao_m in the denominator.
