### ISSUE TITLE
lab 5 simulink

### ISSUE THREAD

**Issue by mich-svg** [AreteQin/MECH371#13]
![cap_1](https://github.com/AreteQin/MECH371/assets/148802023/8c6bd931-1005-41cc-9916-17a81b7f90ab)
Im trying to complete question 1 experiment 1 for lab 5 and my scope looks like this. Not 100% sure why the output looks like that.

**Comment by AreteQin** [comment]
Hi

What are the values of you kt, ko, kp and ki
