### ISSUE TITLE
LAB 6

### ISSUE THREAD

**Issue by paritoasted** [AreteQin/MECH371#14]
![image](https://github.com/AreteQin/MECH371/assets/105744609/2bd89ff8-76cd-40bf-90b3-c32321bbaeab)
For this question  do we just put a screenshot of our block diagram?

**Comment by AreteQin** [comment]
Hi

Please run it with step input.

**Comment by businessminder** [comment]
so if we are run it with step input thats all? do we have to show the different screenshots for the different K, Ti, and Td values?

**Comment by AreteQin** [comment]
Please put some example screenshots for discussion.
