### ISSUE TITLE
LAB 6 experiment 2_conversion

### ISSUE THREAD

**Issue by UnicornsDoExist** [AreteQin/MECH371#15]
when we measured PO, steady state, etc for part 2 of lab 6, the values obtained are in degrees in the y axis, right?
Do I have to convert them to Volts, to compare with the data from lab 5?

If so, what is the conversion factor to go from degrees to volts?

Thanks

**Comment by AreteQin** [comment]
Yes, please use Ko and Ki provided on page 8 to convert them.
