### ISSUE TITLE
Lab 3 Q3

### ISSUE THREAD

**Issue by chyaboi1** [AreteQin/MECH371#5]
for experiment 3, how do we find KM? I know KM=Kp*Km but where do we get the values of Kp and Km from? Do we use the previous lab? Also, what do we use as the time constant Tao_m

**Comment by AreteQin** [comment]
Hi! 
All values, Tao, Kp, and Km can be found from your previous lab. All groups have different values.

**Comment by chyaboi1** [comment]
Thanks. Does KM=1243.04 make sense? I used the positive value of Kp=9.14 and Km=136

**Comment by AreteQin** [comment]
Yes
