### ISSUE TITLE
lab 3 questtions

### ISSUE THREAD

**Issue by businessminder** [AreteQin/MECH371#8]
what is N in eq3.3? what is Ko?
![image](https://github.com/AreteQin/MECH371/assets/145087405/d6d9b3e1-003b-4916-82ef-a10166ef1be1)

**Comment by AreteQin** [comment]
Refer to this Question, please. #6

**Comment by businessminder** [comment]
what about N? i cant find it there

**Comment by AreteQin** [comment]
It is 30
